### PR TITLE
On hit effects

### PR DESCRIPTION
**Pull request by gatperdut**
I am not too sure about this.

Somehow I ended up having to look in 2 places:

One of them you already did, just needed to be shown. It's the `Effect.Item_Set_Melee_Effect` and `Effect.Item_Set_Ranged_Effect` in `BGEntity`.

The other needs to go through the items and parse its effects, abilities, and the effects of the abilities. Which is weird, because I would think the previous step takes care of that.

In any case I wouldn't merge. Some stuff that doesn't make sense or is incomplete is showing up.

But maybe you can take a look and tell me what you think?

### CODE REVIEW

**Comment by tapahob** [comment]
I'll have a look in the evening

**Comment by tapahob** [comment]
We can't leave it like this:
image
There should be some filtering / proper human readable interpretations

**Comment by tapahob** [comment]
I've also checked Balor:
image
it seems like the save type is incorrect - (it says its spell when it should be death)

**Comment by gatperdut** [comment]
Yes I agree. I think i'll leave the branch as is, that was as far as my knowledge would get me, in case someone figures it out

**Comment by tapahob** [comment]
> Yes I agree. I think i'll leave the branch as is, that was as far as my knowledge would get me, in case someone figures it out

But you did so much already - I'll see what I can get off of it

**Comment by tapahob** [comment]
Guess whaaat? :)
1nhIzTAt2O

**Comment by gatperdut** [comment]
> > Yes I agree. I think i'll leave the branch as is, that was as far as my knowledge would get me, in case someone figures it out
> 
> But you did so much already - I'll see what I can get off of it

Yes, but I was seriously struggling by the end of it :joy: very uncertain about what I was doing.

Thank you for taking a look. I'll fire it up in a bit, but it looks awesome!

**Comment by gatperdut** [comment]
> Guess whaaat? :) 1nhIzTAt2O

:heart_eyes:

**Comment by tapahob** [comment]
Just pushed another fix - this one should be rock-solid

**Comment by gatperdut** [comment]
Another one:
bentley

**Comment by tapahob** [comment]
> Another one: bentley
Thanks for the reports!  
Can you check what this dagger is exactly?
The only way it can be spell -1 when both its spell names are -1, I believe.

Also, if you could please pay attention  to the saving throw types of weapon onhit effects. I was checking it against Corsomyr, Silver sword (planetar's) and Balor's skull - Got the death save and no save right (hopefully), but the other types still require checking

**Comment by gatperdut** [comment]
Ah yes, I should have mentioned the excellent dagger - that's from the SCS component that transforms many +1 weapons into "fine" ones. So it's looking good there.

I'll keep an eye on mismatched info regarding saving throws types/penalties :+1:

**Comment by tapahob** [comment]
> Ah yes, I should have mentioned the excellent dagger - that's from the SCS component that transforms many +1 weapons into "fine" ones. So it's looking good there.
> 
> I'll keep an eye on mismatched info regarding saving throws types/penalties 👍

Pretty sure excellent daggers don't have any "cast spell" effects on them, so its very suspicious.
I was thinking if I should omit the "use type" abilities from the items (like aoe dispell on Corsomyr) as technically they aren't "on-hit" effects

**Comment by gatperdut** [comment]
About the excellent/fine weapons: agreed. I thought it might have been some shenanigan introduced by SCS but I can't seem to find any reference to it in NearInfinity.

The AoE dispell and similar are good candidates to be omitted if problematic, I think - it's pretty obvious that a green ball of magic is coming toward you, so the feedback is there ("Dispel effects" in the log).

When it comes to on-hit effects, for me the greatest offender was Berena Elkan. She's normally a wizard slayer, so she applies spell failure. But in Ascension she gets Spellstrike (!) + Breach on every hit.

**Comment by tapahob** [comment]
> About the excellent/fine weapons: agreed. I thought it might have been some shenanigan introduced by SCS but I can't seem to find any reference to it in NearInfinity.
> 
> The AoE dispell and similar are good candidates to be omitted if problematic, I think - it's pretty obvious that a green ball of magic is coming toward you, so the feedback is there ("Dispel effects" in the log).
> 
> When it comes to on-hit effects, for me the greatest offender was Berena Elkan. She's normally a wizard slayer, so she applies spell failure. But in Ascension she gets Spellstrike (!) + Breach on every hit.

Oh Im excited to see how radar would react to her

**Comment by gatperdut** [comment]
I checked yesterday, and I'm like 80.33% sure it displayed all 3 effects (spell failure, spellstrike, breach), but I can't remember the exact description it showed. I'll get a screenshot later.

**Comment by gatperdut** [comment]
Here are some findings:

Hakeashars look awesome:
hakeashar

And so does the Mace of Disruption, both the save type and the penalty are correct.
macedisrupt


Berena is almost right:
berenaelkan

I believe Mindflayers might be missing the int drain, but it's odd - I'm almost sure I saw it at some point!
mindflayer

In a Frost Salamader I noticed again the "cast spell at creature: -1" bit. In this case I'm almost sure after digging in NI a bit that it's the aura, the SPL it references has an effect for cold damage.
frostsalamander

I also went looking for the sword Gram. I am not quite sure what is going on, I took a pic of both the inventory description and the listed effects.
gramswordgrief

Oh and dragons show the wing buffet ability :D

**Comment by tapahob** [comment]
Could you please check it with the latest release?

And lets create a new issue for that

**Comment by gatperdut** [comment]
Can't wait to try!

I'll port the stuff from above in this issue to the new issue if necessary, and add any other findings.

**Comment by tapahob** [comment]
I've just pushed an update for the on-hit protection removals, could you please check it?
I don't have ascention installed so can't really test - if its fine I'll update the release

**Comment by gatperdut** [comment]
yap, will do!

**Pull request merged**
