### PR TITLE
[Refactoring] MainWindow.xaml.cs

### PR DESCRIPTION
**Pull request by Nesae-avi**
- Used coding conventions for private fields and method names
- Moved object initialization into member definition
- Renamed `deleteMe` into `DeleteEnemyControlByTag`
- Renamed `addOrRemove` into `ChangeEnemyControlStateByEntity`
- Used `nameof()` instead of string literal

### CODE REVIEW

**Comment by tapahob** [comment]
On the coding convention thing - I use the lowercase naming for all things private, which I believe is a standard for C#. In your case (the C++ way, right?) there is no difference in naming of private and public functions.

I'm okay with the rest

**Comment by Nesae-avi** [comment]
According to C# coding conventions we use pascal casing for naming public methods. I have not seen any coding convention that distinguished between public and private methods nor do I see any benefit from doing so since the accessibility level is already distinguished by adding access modifiers.

In the case of having two similar methods, one for public use and another for internal use we can prefix it with `Internal` keyword eg. `GetEntity` and `InternalGetEntity`, therefore making them easily distinguishable.

Regarding naming of the private / internal fields: `use camel casing ("camelCasing") when naming private or internal fields, and prefix them with _.` 

Reference: https://learn.microsoft.com/en-us/dotnet/csharp/fundamentals/coding-style/coding-conventions

**Comment by tapahob** [comment]
Myabe its not the standard, but I wrote the whole project with it in mind - I see no point changing it at this stage

**Comment by Nesae-avi** [comment]
It is a valid point. I changed that seeing some of the methods named one way and the rest another - not knowing if it was intentional or oversights. 

How about naming event handlers `ListView_SelectionChanged`  or `listView_SelectionChanged`?

**Comment by tapahob** [comment]
Im okay with that

**Comment by Nesae-avi** [comment]
I have reverted the change.

**Pull request merged**
